---
- hosts: all
  become: true
  tasks:
    - name: Provisioning common configuration
      include_tasks: common.yaml
    - name: Provisioning kubernetes and cluster dependencies
      include_tasks: kube.yaml
    - name: Initialize kubernetes cluster
      command: kubeadm init --apiserver-advertise-address="192.168.40.100" --apiserver-cert-extra-sans="192.168.40.100" --node-name kube-master-node --pod-network-cidr=192.168.0.0/16
    - name: setup kubeconfig for vagrant user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/vagrant/.kube
        - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
        - chown vagrant:vagrant /home/vagrant/.kube/config
      args:
        warn: false
    - pause:
        prompt: "Give it a time for Kubernetes pods to started"
        minutes: 1
    - name: Copy Kubernetes deployment manifest
      copy:
        src: "files/{{ item }}"
        dest: "/tmp/{{ item }}"
      with_items:
        - "install-calico.yaml"
        - "install-metallb.yaml"
        - "install-ingress-nginx.yaml"
    - name: Install calico and metallb and ingress nginx
      become: false
      command: "kubectl apply -f {{ item }}"
      with_items:
        - "/tmp/install-calico.yaml"
        - "/tmp/install-metallb.yaml"
        - "/tmp/install-ingress-nginx.yaml"
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command
    - name: Copy join command to local file
      become: false
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="files/exported-join-command"

